## local config
component:
  name: 'iam_policy'
  mapping: ['.']
  dependsOn: ['../iam_role']
  template:
    data:
      aws_iam_policy_document:
        iam_policy:
          statement:
            - sid: ${var.iam_policy_sid}
              actions: ${split(",",var.iam_policy_actions)}
              resources: ${split(",",var.iam_policy_resources)}
    resource:
      aws_iam_policy:
        iam_policy:
          description: ${var.iam_policy_description}
          name: ${var.iam_policy_name}
          path: ${var.iam_policy_path}
          policy: ${data.aws_iam_policy_document.iam_policy.json}
    output:
      id:
        value: ${aws_iam_policy.iam_policy.id}
      thub_id:
        value: ${aws_iam_policy.iam_policy.id}
      arn:
        value: ${aws_iam_policy.iam_policy.arn}
      name:
        value: ${aws_iam_policy.iam_policy.name}
      path:
        value: ${aws_iam_policy.iam_policy.path}
      policy:
        value: ${aws_iam_policy.iam_policy.policy}
    variable:
      iam_policy_name:
        type: string
      iam_policy_description:
        type: string
      iam_policy_path:
        type: string
      iam_policy_sid:
        type: string
      iam_policy_actions:
        type: string
      iam_policy_resources:
        type: string
    tfvars:
      iam_policy_actions: lambda:*
      iam_policy_description: Managed by TerraHub
      iam_policy_name: iam_policy
      iam_policy_path: /
      iam_policy_resources: '*'
      iam_policy_sid: default
