project:
  name: terraform-aws-automation-demo
  code: 7356626c
  include:
    - .
  exclude:
    - '**/.terraform/*'
    - '**/node_modules/*'
    - '**/.git/**'

terraform:
  version: 0.12.20
  varFile:
    - default.tfvars

template:
  locals:
    account_id: 123456789012
    region: us-east-1
  terraform:
    backend:
      local:
        path: >-
          /tmp/.terrahub/local_backend/terraform-aws-automation-demo/${tfvar.terrahub["component"]["name"]}/terraform.tfstate
