project:
  name: terraform-aws-automation-demo
  code: 7356626c
  include:
    - .
  exclude:
    - '**/.terraform/*'
    - '**/node_modules/*'
    - '**/.git/**'

template:
  terraform:
    backend:
      local:
        path: /tmp/.terrahub/local_backend/demo-terraform-automation-aws/${tfvar.terrahub["component"]["name"]}/terraform.tfstate

terraform:
  version: 0.12.19
  varFile:
    - default.tfvars
