project:
  name: demo-terraform-automation-aws
  code: 7356626c
  include:
    - .
  exclude:
    - '**/.terraform/*'
    - '**/node_modules/*'
    - '**/.git/**'
terraform:
  varFile:
    - default.tfvars
  version: 0.11.11
template:
  locals:
    account_id: 123456789012
    region: us-east-1
  provider:
    aws:
      region: '${local.region}'
      allowed_account_ids:
        - '${local.account_id}'
