## project config
project:
  name: demo-terraform-automation-aws
  code: 7356626c
  include:
  - '.'
  exclude:
  - '**/.terraform/*'
  - '**/node_modules/*'

## terraform config
terraform:
  varFile:
  - default.tfvars
  var:
    account_id: 123456789012
    region: us-east-1
