project:
  name: terraform-aws-automation-demo
  code: 7356626c
  include:
    - .
  exclude:
    - '**/.terraform/*'
    - '**/node_modules/*'
    - '**/.git/**'

terraform:
  version: 0.12.19
  varFile:
    - default.tfvars

template:
  terraform:
    backend:
      local:
        path: /tmp/.terrahub/local_backend/terraform-aws-automation-demo/${tfvar.terrahub["component"]["name"]}/terraform.tfstate
