component:
  name: api_gateway_rest_api
  mapping:
    - .
  dependsOn:
    - ../lambda
  template:
    resource:
      aws_api_gateway_rest_api:
        api_gateway_rest_api:
          name: DemoApi7356626c
          body: '${data.template_file.swagger.rendered}}'
          description: Managed by TerraHub
    output:
      id:
        value: '${aws_api_gateway_rest_api.api_gateway_rest_api.id}'
      thub_id:
        value: '${aws_api_gateway_rest_api.api_gateway_rest_api.id}'
      root_resource_id:
        value: '${aws_api_gateway_rest_api.api_gateway_rest_api.root_resource_id}'
      execution_arn:
        value: '${aws_api_gateway_rest_api.api_gateway_rest_api.execution_arn}'
      endpoint_configuration:
        value: >-
          ${aws_api_gateway_rest_api.api_gateway_rest_api.endpoint_configuration}
      created_date:
        value: '${aws_api_gateway_rest_api.api_gateway_rest_api.created_date}'
    terraform:
      backend:
        s3:
          bucket: data-lake-terrahub-us-east-1
          key: terraform/mitocgroup/demo-terraform-automation-aws/api_gateway_rest_api/terraform.tfstate
          region: us-east-1
          workspace_key_prefix: terraform_workspaces
    data:
      template_file:
        swagger:
          template: '${file("${local.project["path"]}/api_swagger.json.tpl")}'
          vars: '${map("account_id","${local.account_id}")}'
