## local config
component:
  name: api_gateway_rest_api
  dependsOn: ['../lambda']
  mapping: ['.']
  template:
    terraform:
      backend:
        local:
          path: ~/.terrahub/local_backend/api_gateway_rest_api/terraform.tfstate
    data:
      local_file:
        swagger:
          filename: ${local.component["path"]}/api-swagger.json
    resource:
      aws_api_gateway_rest_api:
        api_gateway_rest_api:
          body: ${data.local_file.swagger.content}
          depends_on:
          - data.local_file.swagger
          description: Managed by TerraHub
          name: DemoApi7356626c
    output:
      id:
        value: ${aws_api_gateway_rest_api.api_gateway_rest_api.id}
      created_date:
        value: ${aws_api_gateway_rest_api.api_gateway_rest_api.created_date}
      name:
        value: ${aws_api_gateway_rest_api.api_gateway_rest_api.name}
      execution_arn:
        value: ${aws_api_gateway_rest_api.api_gateway_rest_api.execution_arn}
