## local config
component:
  name: 'iam_user_group_membership'
  mapping: ['.']
  dependsOn: ['../iam_user']
  template:
    resource:
      aws_iam_user_group_membership:
        iam_user_group_membership:
          groups: ${var.iam_groups_name}
          user: ${var.iam_user_name}
    output:
      user:
        value: ${aws_iam_user_group_membership.iam_user_group_membership.user}
      groups:
        value: ${aws_iam_user_group_membership.iam_user_group_membership.groups}
    variable:
      iam_user_name:
        type: string
      iam_groups_name:
        type: list
    tfvars:
      iam_groups_name: [iam_user_group_membership]
      iam_user_name: iam_user_group_membership
