component:
  name: iam_role
  mapping:
    - .
  template:
    resource:
      aws_iam_role:
        iam_role:
          assume_role_policy: '${file("${local.project["path"]}/iam_trust_policy.json.tpl")}'
          description: Managed by TerraHub
          force_detach_policies: false
          name: DemoAWSLambdaExecRole7356626c
          path: /
      aws_iam_role_policy:
        iam_role:
          name: DemoAWSLambdaExecPolicy7356626c
          policy: '${data.template_file.iam_role_policy.rendered}'
          role: '${aws_iam_role.iam_role.id}'
    output:
      id:
        value: '${aws_iam_role.iam_role.id}'
      thub_id:
        value: '${aws_iam_role.iam_role.id}'
      create_date:
        value: '${aws_iam_role.iam_role.create_date}'
      unique_id:
        value: '${aws_iam_role.iam_role.unique_id}'
      name:
        value: '${aws_iam_role.iam_role.name}'
      arn:
        value: '${aws_iam_role.iam_role.arn}'
    terraform:
      backend:
        s3:
          bucket: data-lake-terrahub-us-east-1
          key: terraform/mitocgroup/demo-terraform-automation-aws/iam_role/terraform.tfstate
          region: us-east-1
          workspace_key_prefix: terraform_workspaces
    data:
      template_file:
        iam_role_policy:
          template: '${file("${local.project["path"]}/iam_assume_policy.json.tpl")}'
          vars: '${map("account_id","${local.account_id}")}'
