## local config
component:
  name: iam_lambda
  mapping: ['.']
  template:
    terraform:
      backend:
        local:
          path: ~/.terrahub/local_backend/iam_lambda/terraform.tfstate
    data:
      aws_iam_policy_document:
        iam_role_policy:
          statement:
          - actions:
            - lambda:getFunctionConfiguration
            - lambda:InvokeFunction
            effect: Allow
            resources:
            - arn:aws:lambda:us-east-1:${local.account_id}:function:*
          - actions:
            - apigateway:*
            effect: Allow
            resources:
            - arn:aws:apigateway:us-east-1:${local.account_id}:*
          - actions:
            - ec2:CreateNetworkInterface
            - ec2:DescribeNetworkInterfaces
            - ec2:DeleteNetworkInterface
            effect: Allow
            resources:
            - '*'
          - actions:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:DescribeLogGroups
            - logs:DescribeLogStreams
            - logs:PutLogEvents
            - logs:GetLogEvents
            - logs:FilterLogEvents
            effect: Allow
            resources:            
            - arn:aws:logs:*:${local.account_id}:*
          - actions:
            - cloudwatch:setAlarmState
            effect: Allow
            resources:            
            - '*'
          - actions:
            - ec2:CreateNetworkInterface
            - ec2:DescribeNetworkInterfaces
            - ec2:DeleteNetworkInterface
            effect: Allow
            resources:
            - '*'
        iam_trust_policy:
          statement:
          - actions:
            - sts:AssumeRole
            effect: Allow
            principals:
            - identifiers:
              - apigateway.amazonaws.com
              - lambda.amazonaws.com
              type: Service
    resource:
      aws_iam_role:
        iam_aws_lambda_exec:
          assume_role_policy: ${data.aws_iam_policy_document.iam_trust_policy.json}
          description: Managed by TerraHub
          force_detach_policies: false
          name: DemoLambdaAWSExec7356626c
          path: /
      aws_iam_role_policy:
        iam_aws_lambda_exec:
          name: DemoLambdaAWSExecPolicy7356626c
          policy: ${data.aws_iam_policy_document.iam_role_policy.json}
          role: ${aws_iam_role.iam_aws_lambda_exec.id}
    output:
      arn:
        value: ${aws_iam_role.iam_aws_lambda_exec.arn}
      create_date:
        value: ${aws_iam_role.iam_aws_lambda_exec.create_date}
      unique_id:
        value: ${aws_iam_role.iam_aws_lambda_exec.unique_id}
      name:
        value: ${aws_iam_role.iam_aws_lambda_exec.name}
      description:
        value: ${aws_iam_role.iam_aws_lambda_exec.description}
