component:
  name: api_gateway_deployment
  mapping:
    - .
  dependsOn:
    - api_gateway_rest_api
  template:
    resource:
      aws_api_gateway_deployment:
        api_gateway_deployment:
          rest_api_id: '${data.aws_api_gateway_rest_api.api_gateway_deployment.id}'
          stage_name: demo
          description: Managed by TerraHub
          stage_description: >-
            ${format("%s %s", var.api_gateway_deployment_stage_name,
            timestamp())}
    variable:
      api_gateway_deployment_stage_name:
        type: string
    output:
      id:
        value: '${aws_api_gateway_deployment.api_gateway_deployment.id}'
      thub_id:
        value: '${aws_api_gateway_deployment.api_gateway_deployment.id}'
      invoke_url:
        value: '${aws_api_gateway_deployment.api_gateway_deployment.invoke_url}'
      execution_arn:
        value: '${aws_api_gateway_deployment.api_gateway_deployment.execution_arn}'
      created_date:
        value: '${aws_api_gateway_deployment.api_gateway_deployment.created_date}'
    terraform:
      backend:
        local:
          path: /tmp/.terrahub/local_backend/api_gateway_deployment/terraform.tfstate
    data:
      aws_api_gateway_rest_api:
        api_gateway_deployment:
          name: DemoApi7356626c
    tfvars:
      api_gateway_deployment_stage_name: 'Deployed at'
